--SELECT NEXT VALUE FOR ImageRepository_Sequence;
--ImageRepository_Sequence
CREATE SEQUENCE ImageRepository_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SEORepository_Sequence
CREATE SEQUENCE SEORepository_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--CategoryMaster_Sequence
CREATE SEQUENCE CategoryMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SubCategoryMaster_Sequence
CREATE SEQUENCE SubCategoryMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--TypeCategoryMaster_Sequence
CREATE SEQUENCE TypeCategoryMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--CategoryMappings_Sequence
CREATE SEQUENCE CategoryMappings_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--ProductMaster_Sequence
CREATE SEQUENCE ProductMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--CompanyMaster_Sequence
CREATE SEQUENCE CompanyMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--BrandMaster_Sequence
CREATE SEQUENCE BrandMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SpecificationMaster_Sequence
CREATE SEQUENCE SpecificationMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SpecificationValuesMaster_Sequence
CREATE SEQUENCE SpecificationValuesMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--ProductSpecification_Sequence
CREATE SEQUENCE ProductSpecification_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SKUMaster_Sequence
CREATE SEQUENCE SKUMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SKUInventory_Sequence
CREATE SEQUENCE SKUInventory_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SKUDiscount_Sequence
CREATE SEQUENCE SKUDiscount_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--VendorMaster_Sequence
CREATE SEQUENCE VendorMaster_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

--SKUVendor_Sequence
CREATE SEQUENCE SKUVendor_Sequence
AS BIGINT
START WITH 1
INCREMENT BY 1
MINVALUE 1 
MAXVALUE 99999999999  
NO CYCLE
NO CACHE;

